# Generated by Django 5.2.7 on 2025-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerverification',
            name='id_card_pdf',
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='document',
            field=models.FileField(default='temporary.pdf', upload_to='verification_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
