# Generated by Django 5.2.7 on 2025-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
