# Generated by Django 5.2.7 on 2025-11-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_primary', 'uploaded_at']},
        ),
    ]
