# Generated by Django 5.2.7 on 2025-11-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_sellerverification_id_card_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
